<a href="https://colab.research.google.com/github/ADRIANVM117/proyectos_propios/blob/main/proyectos_propios/actuaria/guia2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 1

## Gauss-Jordan 

In [1]:
# Método de Gauss-Jordan
# Solución a Sistemas de Ecuaciones
# de la forma A.X=B

import numpy as np
from math import e
from math import log

# INGRESO
A = np.array([[np.pi, -e , np.sqrt(2) , -np.sqrt(3)],
              [np.pi**2 , e**3 , -e**2, 3/4],
              [np.sqrt(5) , - np.sqrt(6)/2 ,1 , - np.sqrt(8)],
              [np.pi**3 , log(3) , -np.sqrt(7) , 1/9]])

B = np.array([[np.sqrt(11)],
              [0],
              [np.log(np.pi)],
              [np.sqrt(19)]],float)

# PROCEDIMIENTO
casicero = 1e-15 # Considerar como 0

# Evitar truncamiento en operaciones
A = np.array(A,dtype=float) 

# Matriz aumentada
AB = np.concatenate((A,B),axis=1)
AB0 = np.copy(AB)

# Pivoteo parcial por filas
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dondemax = np.argmax(columna)
    
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal
        
AB1 = np.copy(AB)

# eliminacion hacia adelante
for i in range(0,n-1,1):
    pivote = AB[i,i]
    adelante = i + 1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
AB2 = np.copy(AB)

# elimina hacia atras
ultfila = n-1
ultcolumna = m-1
for i in range(ultfila,0-1,-1):
    pivote = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
X = np.copy(AB[:,ultcolumna])
X = np.transpose([X])


# SALIDA
print('Matriz aumentada:')
print(AB0)
print('Pivoteo parcial por filas')
print(AB1)
print('eliminacion hacia adelante')
print(AB2)
print('eliminación hacia atrás')
print(AB)
print('solución de X: ')
print(X)

Matriz aumentada:
[[ 3.14159265 -2.71828183  1.41421356 -1.73205081  3.31662479]
 [ 9.8696044  20.08553692 -7.3890561   0.75        0.        ]
 [ 2.23606798 -1.22474487  1.         -2.82842712  1.14472989]
 [31.00627668  1.09861229 -2.64575131  0.11111111  4.35889894]]
Pivoteo parcial por filas
[[31.00627668  1.09861229 -2.64575131  0.11111111  4.35889894]
 [ 9.8696044  20.08553692 -7.3890561   0.75        0.        ]
 [ 3.14159265 -2.71828183  1.41421356 -1.73205081  3.31662479]
 [ 2.23606798 -1.22474487  1.         -2.82842712  1.14472989]]
eliminacion hacia adelante
[[31.00627668  1.09861229 -2.64575131  0.11111111  4.35889894]
 [ 0.         19.73583777 -6.5468873   0.71463223 -1.38748063]
 [ 0.          0.          0.7436346  -1.64084945  2.67604815]
 [ 0.          0.          0.         -1.11614433 -1.98990302]]
eliminación hacia atrás
[[ 1.          0.          0.          0.          0.69317951]
 [ 0.          1.          0.          0.          2.36386018]
 [ 0.          0.   

# Ejercicio 2 
## Matriz inversa 

In [9]:
A_1 = np.array([[25,-300,1050,-1400,630],
                [-300,4800,-18900,26880,-12600],
                [1050,-18900,79380,-117600,56700],
                [-1400,26880 ,-117600,179200,-88200],
                [630,-12600,56700,-88200,44100]], float)

B = np.array([[1],
              [0],
              [1],
              [0],
              [1]])
inversa = np.linalg.inv(A)
solucion = np.matmul(inversa,B)
print(A_1)


LinAlgError: ignored

# Ejercicio 3 
## Metodo LU