<a href="https://colab.research.google.com/github/ADRIANVM117/proyectos_propios/blob/main/actuaria/metodos_numericos/metodos_numericos_2p.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2do Parcial

## Solución de sistemas lineales 

- Metodos: 
   - fijos : G.J pivoteo, MI pivoteo, LV, chalesky
   - Iterativos : Gauss- Seidel, Jacobi 
   

In [48]:
import numpy as np 

A = np.array([[2,3,-1],
            [-4, 5, 0]], float)

A[0,:] = A[0,:] / A[0,0]



A[1,:] = A[1,:] - A[1,0]*A[0,:]


temp = np.copy(A[0,:])
A[0,:] = A[1,:]
A[1,:] = temp 


B = np.array([[2,3, 1]], float)# renglon
b = np.array([[2],[3]], float) # columnas 

av = np.concatenate((A,b), axis =1 )  #concatenar filas

# print(av.shape)

a = np.array([[2,3,5,-4], [-3,2,-7,0], [9,-4,6,-1], [-8,1,-1,5]], float)
c = np.array([[7],[-9],[6],[8]], float)


[filas,columnas] = a.shape
renglones = len(c)
if filas == columnas and filas == renglones:
  au = np.concatenate((a,c), axis = 1)
  renglon = 0  # primer pivote 
  for i in range(0,renglones):
    if abs(au[renglon,0]) < abs(au[i,0]):
      renglon+=1
  temp = np.copy(au[0,:])
  au[0,:] = au[renglon,:]
  au[renglon,:] = temp
  au[0,: ]= au[0,:] / au[0,0]
  print(au)                   # dividir el pivote en 1
  
  for i in range(0,filas):
    if i != 0:
      au[i,:] = au[i,:] - au[i,0]* au[0,:]
  print(au)

[[ 1.         -0.44444444  0.66666667 -0.11111111  0.66666667]
 [-3.          2.         -7.          0.         -9.        ]
 [ 2.          3.          5.         -4.          7.        ]
 [-8.          1.         -1.          5.          8.        ]]
[[ 1.         -0.44444444  0.66666667 -0.11111111  0.66666667]
 [ 0.          0.66666667 -5.         -0.33333333 -7.        ]
 [ 0.          3.88888889  3.66666667 -3.77777778  5.66666667]
 [ 0.         -2.55555556  4.33333333  4.11111111 13.33333333]]
